@echo off
echo Starting World News Application in Production Mode (Local Testing)...
echo.
echo Starting Backend Server with Production Config...
start "Backend Server (Prod)" cmd /k "cd backend && npm run dev:prod"
echo.
echo Waiting 3 seconds for backend to start...
timeout /t 3 /nobreak >nul
echo.
echo Starting Frontend Server with Production API...
start "Frontend Server (Prod)" cmd /k "cd frontend && npm run dev:prod"
echo.
echo Both servers are starting...
echo Backend: Using production configuration
echo Frontend: http://localhost:3000 (connecting to production API)
echo.
echo Press any key to exit...
pause >nul