@echo off
echo Starting World News Application in Local Development Mode...
echo.
echo Starting Backend Server...
start "Backend Server" cmd /k "cd backend && npm run dev"
echo.
echo Waiting 3 seconds for backend to start...
timeout /t 3 /nobreak >nul
echo.
echo Starting Frontend Server...
start "Frontend Server" cmd /k "cd frontend && npm run dev:local"
echo.
echo Both servers are starting...
echo Backend: http://localhost:5000
echo Frontend: http://localhost:3000
echo.
echo Press any key to exit...
pause >nul